schema = 1
name = "fuzz-1-9"
input = 'iozp$ezhhw.<Esc> mRdwno$b$o$xqzddggyy"1ulmtO<Esc>j<Esc>1u:<Esc>pa<Esc>?nsdyyk <C-w>s<CR>Ocfp<Esc>lz$zaxwggei"a<Esc>krc glbnpshuj$1yyhspmt$lijnk<Esc><Esc>bwkrx$uf<Esc>qgpwx<C-w>shxi<Esc>ny"ad yumz dd d0bdwvsdykdckpnfcc'
engine_pin = "v0.12.4"
ext_set = "default"
