schema = 1
name = "fuzz-1-117"
input = 'dww<CR>x0ovyvkdwiobforpylvz<Esc>:xiokd<CR>z<C-w>vmke<C-v>dohR<Esc>m/h"0lrkabdhpscys<CR><Esc>"1zvdjo qtctrdiid0Vdscofxtnpvlfpq"0p<Esc>n f0iwa$!y<Esc>fpeb<Esc>x$gxbgg"0i$odyxreOVtbu<CR><C-v>taeddiwleOaoppi rwi'
engine_pin = "v0.12.4"
ext_set = "default"
