schema = 1
name = "fuzz-2-95"
input = 'ljGwyfkxxuhdgTucxhd$c0kxikk<Esc>ccevcqsdc0iocbeiujluakb<Esc>ddydgljttkbbq<Esc>$bkdaVseddbuyyyo<Esc>ddxuvbathadcdwvhjjeddxbd$bys<Esc>tkjodhqyy0rruhkvdwwwk<Esc>yxgs"axpmabRiomdbs1bcjpwpo'
engine_pin = "v0.12.4"
ext_set = "default"
