//! Renders the published compat-evidence page (`docs/compat.md`) from a
//! prior compat run's `compat/results.json` rows. Pure string rendering:
//! reading the results file, reading `.engine-pin`, and writing the page
//! file stay in `bin/oracle.rs`'s `page` arm, so every rendering and
//! staleness-refusal decision here is testable without touching the
//! filesystem or spawning nvim.
//!
//! Staleness is enforced here, not merely documented on the page: a row
//! whose recorded engine pin differs from the current `.engine-pin` value
//! aborts rendering with [`PageError::StalePin`], so an engine-pin bump
//! forces a full compat re-run before the page can regenerate.

use std::path::Path;

use thiserror::Error;

use crate::results::{ResultsFile, ScenarioResult, ScenarioStatus};

/// Reasons [`render_page`] refuses to render.
#[derive(Debug, Error)]
pub enum PageError {
    /// A results row was produced against a different engine pin than the
    /// one `.engine-pin` currently names, so the recorded evidence no
    /// longer describes the pinned engine.
    #[error(
        "compat results are stale: scenario {scenario} records engine pin \
         {results_pin} but .engine-pin names {current_pin}; re-run `task \
         compat` against the current pin, then regenerate the page"
    )]
    StalePin {
        scenario: String,
        results_pin: String,
        current_pin: String,
    },
    /// The results document holds no rows at all -- there is no evidence to
    /// publish, which is different from evidence that happens to be stale.
    #[error("compat results contain no rows; run `task compat` first")]
    Empty,
}

/// A rendered page plus the summary fields the `page` subcommand's one-line
/// report prints (`wrote docs/compat.md (N rows, pin vX.Y.Z, <date>)`),
/// returned together so the report can never disagree with the page it
/// describes.
#[derive(Debug, Clone)]
pub struct RenderedPage {
    pub markdown: String,
    pub rows: usize,
    pub engine_pin: String,
    /// The latest `date` any row carries. Rows are all stamped by the same
    /// run in the whole-matrix case; taking the maximum keeps the summary
    /// honest for a single-scenario re-run that rewrote the file with a
    /// newer date.
    pub run_date: String,
}

/// Renders the full `docs/compat.md` document from `results`, refusing if
/// the recorded evidence is stale relative to `current_pin` (the trimmed
/// `.engine-pin` value).
///
/// # Errors
///
/// Returns [`PageError::Empty`] if `results` has no rows, or
/// [`PageError::StalePin`] naming the first row whose recorded engine pin
/// differs from `current_pin`.
pub fn render_page(results: &ResultsFile, current_pin: &str) -> Result<RenderedPage, PageError> {
    if results.results.is_empty() {
        return Err(PageError::Empty);
    }
    for row in &results.results {
        if row.engine_pin != current_pin {
            return Err(PageError::StalePin {
                scenario: scenario_stem(row).to_string(),
                results_pin: row.engine_pin.clone(),
                current_pin: current_pin.to_string(),
            });
        }
    }
    let run_date = results
        .results
        .iter()
        .map(|row| row.date.as_str())
        .max()
        .unwrap_or("")
        .to_string();

    let mut page = String::new();
    page.push_str("# Compat evidence\n\n");
    page.push_str(
        "Generated by `task oracle -- page` from `compat/results.json`; \
         regenerate with `task compat && task oracle -- page`. Do not edit \
         by hand: every row, including its date, is machine-stamped by the \
         compat runner.\n\n",
    );
    page.push_str(&format!("- Engine pin: `{current_pin}`\n"));
    page.push_str(&format!("- Run date: {run_date}\n"));
    page.push_str(&format!("- Rows: {}\n\n", results.results.len()));
    page.push_str("## Coverage model\n\n");
    page.push_str(
        "Rows cover the top-N by plugin-manager download rank per compat \
         class, currently the named floor in section 13.3 of the design \
         spec: every UI-owning plugin asserted per scenario state, the \
         semantic and UI-adjacent classes alongside, a cold lazy.nvim \
         bootstrap scenario, and the maintainer's standing daily-config \
         scenario. Version cells are the short commit hashes recorded in \
         the scenario fixture's lazy.nvim lockfile \
         (`compat/fixtures/<fixture>/nvim/lazy-lock.json`); `-` marks a row \
         whose scenario has no fixture or whose fixture lockfile does not \
         name the plugin.\n\n",
    );
    page.push_str("## Reading a result cell\n\n");
    page.push_str(
        "`OK (engine-noise subtracted: ...)` is a row whose state runs the \
         user's own configuration unadjusted: its epilogue subtracts exactly \
         the errors the pinned engine raises on that same configuration with \
         no `view` involved, and the cell names every line it subtracted. \
         `EXPECTED FAILURE` is a row the suite expects red today, listed in \
         the runner's own expected-red manifest and carrying what has to \
         become true for it to go green; the run fails if such a row passes, \
         so the manifest cannot outlive the defect. `FAILED` is an unplanned \
         red and fails the run.\n\n",
    );
    page.push_str("## Staleness rule\n\n");
    page.push_str(
        "Every engine-pin bump re-runs the matrix and re-dates this page. \
         The generator refuses to write the page when any row in \
         `compat/results.json` records an engine pin different from \
         `.engine-pin`, so a pin bump forces a fresh `task compat` run \
         before the page can regenerate.\n\n",
    );
    page.push_str("## Results\n\n");
    page.push_str("| Plugin | Version | Engine pin | Scenario | State | Result | Date |\n");
    page.push_str("| --- | --- | --- | --- | --- | --- | --- |\n");
    for row in &results.results {
        page.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} | {} |\n",
            escape_cell(&row.plugin),
            escape_cell(row.plugin_version.as_deref().unwrap_or("-")),
            escape_cell(&row.engine_pin),
            escape_cell(scenario_stem(row)),
            escape_cell(&row.state),
            escape_cell(&result_cell(row)),
            escape_cell(&row.date),
        ));
    }

    Ok(RenderedPage {
        markdown: page,
        rows: results.results.len(),
        engine_pin: current_pin.to_string(),
        run_date,
    })
}

/// The scenario file's own stem, not `row.plugin`: more than one scenario
/// file can share a plugin name (the cold-bootstrap scenario also drives
/// lualine), which would otherwise make two rows indistinguishable --
/// mirroring the runner's own report-line naming.
fn scenario_stem(row: &ScenarioResult) -> &str {
    Path::new(&row.scenario_path)
        .file_stem()
        .and_then(|stem| stem.to_str())
        .unwrap_or(row.scenario_path.as_str())
}

/// The result column's cell: status word plus, for a non-OK row, the same
/// failing-step/detail facts the runner's report line prints, so the page
/// and the terminal report never tell different stories about one row.
fn result_cell(row: &ScenarioResult) -> String {
    match row.status {
        ScenarioStatus::Ok => row
            .detail
            .as_deref()
            .map_or_else(|| "OK".to_string(), |detail| format!("OK ({detail})")),
        ScenarioStatus::Failed => {
            let step_label = row
                .failing_step
                .map_or_else(|| "epilogue".to_string(), |index| index.to_string());
            format!(
                "FAILED at step {step_label}: {}",
                row.detail.as_deref().unwrap_or("unknown failure")
            )
        }
        ScenarioStatus::ExpectedFailure => format!(
            "EXPECTED FAILURE: {}",
            row.detail.as_deref().unwrap_or("no detail recorded")
        ),
        ScenarioStatus::Skipped => format!(
            "SKIPPED: {}",
            row.detail.as_deref().unwrap_or("no detail recorded")
        ),
    }
}

/// Escapes a value for a one-line markdown table cell: a raw `|` would
/// split the column, and a newline (possible in a failure detail carrying
/// nvim output) would break the row entirely.
fn escape_cell(value: &str) -> String {
    value.replace('|', "\\|").replace(['\n', '\r'], " ")
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]
    use super::*;

    fn row(scenario_stem: &str, plugin: &str) -> ScenarioResult {
        ScenarioResult {
            scenario_path: format!("compat/scenarios/{scenario_stem}.toml"),
            plugin: plugin.to_string(),
            plugin_version: Some("abc1234".to_string()),
            class: "ui-owning".to_string(),
            fixture: Some("heavy".to_string()),
            state: "present".to_string(),
            engine_pin: "v0.12.4".to_string(),
            status: ScenarioStatus::Ok,
            failing_step: None,
            steps_total: 4,
            detail: None,
            elapsed_ms: 100,
            date: "2026-07-19".to_string(),
        }
    }

    fn sample() -> ResultsFile {
        let ok = row("lualine", "lualine");
        let mut failed = row("noice", "noice");
        failed.status = ScenarioStatus::Failed;
        failed.failing_step = Some(2);
        failed.detail = Some("screen never showed marker".to_string());
        let mut skipped = row("daily-config", "daily-config");
        skipped.status = ScenarioStatus::Skipped;
        skipped.plugin_version = None;
        skipped.fixture = None;
        skipped.detail = Some("VIEW_DAILY_CONFIG is unset".to_string());
        let mut expected = row("fidget", "fidget");
        expected.state = "unaccommodated".to_string();
        expected.status = ScenarioStatus::ExpectedFailure;
        expected.failing_step = Some(3);
        expected.detail = Some(
            "expected red until view raises its own notice: E5108 in the notifier".to_string(),
        );
        let mut subtracted = row("neo-tree", "neo-tree");
        subtracted.state = "unaccommodated".to_string();
        subtracted.detail = Some("engine-noise subtracted: E216: No such group".to_string());
        ResultsFile {
            results: vec![ok, failed, skipped, expected, subtracted],
        }
    }

    #[test]
    fn refuses_when_recorded_pin_differs_from_current() {
        let results = sample();
        let err = render_page(&results, "v0.13.0").expect_err("stale pin must refuse");
        assert!(
            matches!(
                &err,
                PageError::StalePin {
                    scenario,
                    results_pin,
                    current_pin,
                } if scenario == "lualine"
                    && results_pin == "v0.12.4"
                    && current_pin == "v0.13.0"
            ),
            "expected StalePin naming the first drifting row, got {err:?}"
        );
        let message = err.to_string();
        assert!(
            message.contains("v0.12.4"),
            "message must name the recorded pin: {message}"
        );
        assert!(
            message.contains("v0.13.0"),
            "message must name the current pin: {message}"
        );
    }

    #[test]
    fn refuses_empty_results() {
        let results = ResultsFile::default();
        let err = render_page(&results, "v0.12.4").expect_err("empty results must refuse");
        assert!(matches!(err, PageError::Empty));
    }

    #[test]
    fn renders_one_table_row_per_result_in_run_order() {
        let page = render_page(&sample(), "v0.12.4").expect("matching pin must render");
        assert_eq!(page.rows, 5);
        assert_eq!(page.engine_pin, "v0.12.4");
        assert!(page
            .markdown
            .contains("| Plugin | Version | Engine pin | Scenario | State | Result | Date |"));
        assert!(page
            .markdown
            .contains("| lualine | abc1234 | v0.12.4 | lualine | present | OK | 2026-07-19 |"));
        assert!(page.markdown.contains(
            "| noice | abc1234 | v0.12.4 | noice | present | \
             FAILED at step 2: screen never showed marker | 2026-07-19 |"
        ));
        assert!(page.markdown.contains(
            "| daily-config | - | v0.12.4 | daily-config | present | \
             SKIPPED: VIEW_DAILY_CONFIG is unset | 2026-07-19 |"
        ));
        // A planned red and a subtraction are only evidence if the committed
        // page says so in its own words -- a row that renders as a plain
        // FAILED or a plain OK is the suppression these two states exist to
        // end, moved into the artifact.
        assert!(page.markdown.contains(
            "| fidget | abc1234 | v0.12.4 | fidget | unaccommodated | \
             EXPECTED FAILURE: expected red until view raises its own notice: \
             E5108 in the notifier | 2026-07-19 |"
        ));
        assert!(page.markdown.contains(
            "| neo-tree | abc1234 | v0.12.4 | neo-tree | unaccommodated | \
             OK (engine-noise subtracted: E216: No such group) | 2026-07-19 |"
        ));
        let lualine_pos = page
            .markdown
            .find("| lualine |")
            .expect("lualine row present");
        let noice_pos = page.markdown.find("| noice |").expect("noice row present");
        assert!(
            lualine_pos < noice_pos,
            "rows must keep the results file's run order"
        );
    }

    #[test]
    fn states_coverage_model_and_staleness_rule() {
        let page = render_page(&sample(), "v0.12.4").expect("matching pin must render");
        assert!(page
            .markdown
            .contains("top-N by plugin-manager download rank"));
        assert!(page.markdown.contains("section 13.3"));
        assert!(page.markdown.contains("## Staleness rule"));
        assert!(page.markdown.contains("refuses"));
    }

    #[test]
    fn run_date_is_the_latest_row_date() {
        let mut results = sample();
        results.results[1].date = "2026-07-21".to_string();
        let page = render_page(&results, "v0.12.4").expect("matching pin must render");
        assert_eq!(page.run_date, "2026-07-21");
        assert!(page.markdown.contains("Run date: 2026-07-21"));
    }

    #[test]
    fn rendering_is_deterministic_for_identical_input() {
        let first = render_page(&sample(), "v0.12.4").expect("render");
        let second = render_page(&sample(), "v0.12.4").expect("render");
        assert_eq!(first.markdown, second.markdown);
    }

    #[test]
    fn pipe_characters_in_detail_are_escaped_in_the_table_cell() {
        let mut results = sample();
        results.results[1].detail = Some("expected |marker| on screen".to_string());
        let page = render_page(&results, "v0.12.4").expect("render");
        assert!(
            page.markdown.contains(r"expected \|marker\| on screen"),
            "a raw pipe inside a cell would split the markdown column"
        );
    }

    #[test]
    fn page_is_ascii_safe_for_the_style_gate() {
        let page = render_page(&sample(), "v0.12.4").expect("render");
        assert!(
            page.markdown.is_ascii(),
            "docs/compat.md is scanned by scripts/check-style.sh; only ASCII survives every check"
        );
    }
}
