[package]
name = "view-surface"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
view-core = { version = "0.0.1", path = "../view-core" }

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name = "render_frame"
harness = false
