[package]
name = "view"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "view"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.103"
clap = { version = "4.6.2", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
view-core = { version = "0.0.1", path = "../view-core" }
view-engine = { version = "0.0.1", path = "../view-engine" }
view-surface = { version = "0.0.1", path = "../view-surface" }
view-tui = { version = "0.0.1", path = "../view-tui" }
